### ISSUE TITLE
Checkbox issue

### ISSUE THREAD

**Issue by j-r-e-i-d** [ceciliamay/obsidianmd-theme-primary#111]
Small screencast here showing checkboxes not rendering properly.
https://www.dropbox.com/s/7vxxzt3s2omnrk1/Screen%20Recording%202022-04-03%20at%2016.47.06.mov?dl=0

**Comment by spcbfr** [comment]
I just noticed this too, I am not sure if it's intentional or not

**Comment by Signynt** [comment]
This issue was fixed on desktop (insider) for me with v.1.4.5 (issue #107), but I also still have the issue on mobile (Android and iOS, both with the most recent release, as well as the most recent insider version).

**Comment by lguenth** [comment]
I had the same issue (Desktop insider as well) but I just checked to see that it was also fixed after upgrading. I have not tested it on mobile.

**Comment by mellowbunstar** [comment]
Same thing as well on the Insider build on both Desktop (Mac) and Mobile (iOS).

![Screen Shot 2022-04-03 at 1 03 31 PM](https://user-images.githubusercontent.com/17543/161446156-038554c2-00b5-40c3-b4c9-127fe958ba46.png)

Love this theme! :D

**Comment by danielnichols** [comment]
It seems that a certain variable name has changed in the insider build:

> Public version:
> ```css
> input[type=checkbox] {
>   height: calc(3px + var(--editor-font-size));
>   width: calc(3px + var(--editor-font-size));
> }
> ```
> Insider version:
> ```css
> input[type=checkbox] {
>   height: calc(3px + var(--font-text-size)); 
>   width: calc(3px + var(--font-text-size)); 
> }
> ```

For now adding the following to a snippet should fix this for both the current version and the insider version (though I haven't tested the insider version)

```css
/* checkbox-temp-fix.css */
input[type=checkbox] {
  height: calc(3px + var(--font-text-size, var(--editor-font-size)));
  width: calc(3px + var(--font-text-size, var(--editor-font-size)));
}
```
