### ISSUE TITLE
Customise padding of preview mode

### ISSUE THREAD

**Issue by kometenstaub** [ceciliamay/obsidianmd-theme-primary#12]
It would be amazing if there was an option (e.g. with the style settings plugin) to match the padding to the left and right side of the edit mode to preview mode, so that the text is as close to the border of a pane in preview mode as it is in edit mode. 

(I'd also be happy to do this with a snippet.)

**Comment by ceciliamay** [comment]
I've also been thinking about that!! I actually consider it as a bug rather than a feature... removing gaps in visual consistency between preview and edit mode is one of the goals for the theme that I think many others using the theme would really appreciate. I'd love to see your snippet and if it works (I'll adjust things if needed), I'll push it for the theme!

**Comment by kometenstaub** [comment]
```css
.markdown-preview-view.is-readable-line-width
.markdown-preview-sizer {
    width: var(--line-width);
/* this was 80% before */
    max-width: 90%;
}
```
