### ISSUE TITLE
[BUG][Live Preview] Inherit in data-link-tags prevent to color internal link

### ISSUE THREAD

**Issue by Mara-Li** [ceciliamay/obsidianmd-theme-primary#128]
**Describe the bug**
I spotted that internal link keep the default text color instead to use the color defined in style settings (`--md-color-reslink`) in LP.

**CSS** 
These lines seem to be the culprit : 
```css
.cm-s-obsidian span.cm-hmd-internal-link span[data-link-tags], .cm-s-obsidian span[data-link-tags] .cm-underline {
  color: inherit;
}
```
Removing color or overriding with `!important` clean the problem, but break my supercharged links snippets. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30244939/166705378-00dbdae3-a86c-4f62-bc60-dd97692a9795.png)

**Desktop:**
 - OS: Windows 11
 - Version : v1.4.6 

**Additional context**
/
