### ISSUE TITLE
[Live Preview Issue] Can't access the end of the file

### ISSUE THREAD

**Issue by Mara-Li** [ceciliamay/obsidianmd-theme-primary#14]
I test the live preview with the theme, and, I saw I can't access the end of the file
![11-14-2021_16-22](https://user-images.githubusercontent.com/30244939/141688526-4a9602cb-c9ce-4ffb-93f4-0e2434f27438.gif)

It seems to be because of the margin around the heading. Because, when I remove it, I have no problem. 

If anyone have this strange bug here is a snippet : 
```css
.markdown-preview-view h1,
.HyperMD-header-1,
.cm-header-1,
.markdown-preview-view h2,
.HyperMD-header-2,
.cm-header-2,
.markdown-preview-view h3,
.HyperMD-header-3,
.cm-header-3,
.markdown-preview-view h4,
.HyperMD-header-4,
.cm-header-4,
.markdown-preview-view h5,
.HyperMD-header-5,
.cm-header-5,
.markdown-preview-view h6,
.HyperMD-header-6,
.cm-header-6 {
    margin: 0 !important;
}
```
