### ISSUE TITLE
Customizability of header size

### ISSUE THREAD

**Issue by HEmile** [ceciliamay/obsidianmd-theme-primary#3]
Hi! Lovely theme, thank you so much :) 
The only gripe I have with it is the size of the headers. I prefer smaller headers like in the Minimal theme. Is it possible to add this to the Style Settings plugin?

**Comment by ceciliamay** [comment]
Thanks for suggesting this @HEmile ! I'll be sure to add this once I start working on the customizations, which will be after the Mobile update (which is very very soon 😉)

**Comment by HEmile** [comment]
Cool, thanks!! That's really not so important to me, either way is fine for me :)

**Comment by zcysxy** [comment]
Yeah the headings are also too BIG for me haha

**Comment by yurimalheiros** [comment]
I added some snippets to fix this in my custom CSS file. I don't know if this is the best way, but it may help:

```css
.markdown-preview-view h1, pre.HyperMD-header.HyperMD-header-1 span, div.HyperMD-header.HyperMD-header-1 span {
    font-size: var(--font-scale-5);
}

.markdown-preview-view h2, pre.HyperMD-header.HyperMD-header-2 span, div.HyperMD-header.HyperMD-header-2 span {
    font-size: var(--font-scale-4);
}

.markdown-preview-view h3, pre.HyperMD-header.HyperMD-header-3 span, div.HyperMD-header.HyperMD-header-3 span {
    font-size: var(--font-scale-3);
}

.markdown-preview-view h4, pre.HyperMD-header.HyperMD-header-4 span, div.HyperMD-header.HyperMD-header-4 span {
    font-size: var(--font-scale-2);
}

.markdown-preview-view h5, pre.HyperMD-header.HyperMD-header-5 span, div.HyperMD-header.HyperMD-header-5 span {
    font-size: var(--font-scale-1);
}

.markdown-preview-view h6, pre.HyperMD-header.HyperMD-header-6 span, div.HyperMD-header.HyperMD-header-6 span {
    font-size: var(--font-scale-1);
}
```
