### ISSUE TITLE
Style buttons in the same way when they're `focus`sed as when they are `hover`ed

### ISSUE THREAD

**Issue by SkepticMystic** [ceciliamay/obsidianmd-theme-primary#4]
I think most themes do this. When a button has the `focus` state, style it the same as when it has `hover`:
```css
.theme-dark .modal button:not(.mod-cta):not(.mod-warning):focus {
    background: var(--color-d-blacker) !important;
}
```
