### ISSUE TITLE
Numbered sub-bullet points

### ISSUE THREAD

**Issue by DutchPete** [ceciliamay/obsidianmd-theme-primary#47]
This is how they are rendered in Live Preview:

![image](https://user-images.githubusercontent.com/10794265/150344424-d424b7b8-e916-4f20-93d1-797661dcfc8b.png)

And this is how they are rendered in Reading/Preview mode:

![image](https://user-images.githubusercontent.com/10794265/150344606-ed7af47d-718d-4cb7-8e9f-878778cd4e2d.png)

I would like to have point 1A shown as `1.1.` in both Live Preview and Reading modes.

I noticed you have this in your theme:
```css
ol {
    list-style-type: decimal;
    margin-left: var(--scale-0-0);
}
ol ol {
    list-style-type: lower-alpha;
}
```

If I replace `lower-alpha` by `decimal`, then point 1A is numbered as `1` only, albeit indented.
What code can I put in a snippet to get point 1A shown as `1.1.` or `1.1`?
