### ISSUE TITLE
Inconsitent space below headings

### ISSUE THREAD

**Issue by nousernameavailableanymore** [ceciliamay/obsidianmd-theme-primary#89]
The space below a heading is inconsistent between reading mode / Live Preview.

When using CSS to adjust the space, it even becomes inconsistent between reading mode / Live Preview and embed preview.
The difference in embed preview seems to come from the "margin-bottom: -0.2em", which only decreases the gap in reading mode a tiny bit but completely removes the gap in embed preview.

CSS used for affected heading:
```css
.markdown-preview-view h1 {
	color: var(--sne-gold-trans);
	text-align: center;
	vertical-align: middle; 
	background-color: var(--code-color);
	margin-bottom: -0.2em !important;
}


.HyperMD-header-1,
.cm-header-1 {
	color: var(--sne-gold-trans);
	text-align: center;
	vertical-align: middle; 
	background-color: var(--code-color);
}
```

![image](https://user-images.githubusercontent.com/45376324/158002509-0aff2f1a-f050-414a-a821-0ac30f94fac5.png)
![image](https://user-images.githubusercontent.com/45376324/158002525-3ee18412-1633-4473-8bf8-179e410056ba.png)

![image](https://user-images.githubusercontent.com/45376324/158002540-31a26694-7440-41e9-ae2e-292467174baf.png)
![image](https://user-images.githubusercontent.com/45376324/158002553-49693e43-030c-4d38-9881-501baa818089.png)
![image](https://user-images.githubusercontent.com/45376324/158002572-9be119e5-ab6e-4c08-b8d2-8154f60e9603.png)
