### ISSUE TITLE
[FR] !important prevent changing color in hovering explorer (css snippet)

### ISSUE THREAD

**Issue by Mara-Li** [ceciliamay/obsidianmd-theme-primary#93]
Hello !
I use a snippet to change the color of my files when hovered. For that, I use : 
```css
.nav-folder-title[data-path^="10."]:hover,
.nav-file-title[data-path^="10."]:hover,
.colorful-active .nav-file-title.is-active[data-path^="10."],
.nav-folder-title.is-active[data-path^="10."] {
    color: var(--F10) !important;
    background-color: var(--bg10) !important;
    filter: saturate(150%);
}
```
But, in your theme : 
```css
.theme-light .nav-folder-title:not([data-path="/"]):hover, .theme-light .nav-file-title:hover {
  color: var(--color-l-gray-80) !important;
  background: var(--color-l-gray-10) !important;
}
```
Prevent me to change the color.
Do you have an idea to override this?
